[versions]
kotlin = "2.4.10"
agp = "9.3.2"
libgdx = "1.14.2"
junit = "4.13.2"
androidx-test-core = "1.7.0"
androidx-test-ext-junit = "1.3.0"
androidx-test-runner = "1.7.0"

[libraries]
gdx = { module = "com.badlogicgames.gdx:gdx", version.ref = "libgdx" }
gdx-backend-lwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "libgdx" }
gdx-backend-android = { module = "com.badlogicgames.gdx:gdx-backend-android", version.ref = "libgdx" }
gdx-platform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "libgdx" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
